#!/bin/bash

python3.6 tests/tcT2.py > tests/test3.in
javac7 tests/Ragil.java
cd tests
java7 "Ragil" < test3.in > test3.out
cd ..


filetype=".java"

for i in `seq 1 17`;
do
	echo "------------------------------" test$i
	time javac7 $1
	echo "------------------------------"
	time java7 ${1%$filetype} < tests/test$i.in > tests/test$i.res
	diff tests/test$i.res tests/test$i.out
done


